spring.application.name=Booksmanagment App

#Database Configuration
spring.datasource.url=jdbc:h2:file:C:/Users/jano2/OneDrive/Desktop/Informatik Semester/4. Semester/SEP Projekt/Code/db
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true